version: "3.8"

services:
  caddy:
    image: caddy:alpine
    container_name: caddy_borda
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_logs:/var/log/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - castelo_edge
      - castelo_web
      - obs
    restart: always

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      - COLLECTIONS=crowdsecurity/caddy crowdsecurity/base-http-scenarios crowdsecurity/linux
    volumes:
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml
      - caddy_logs:/var/log/caddy:ro
      - crowdsec_data:/var/lib/crowdsec/data
    networks:
      - obs
    restart: always

  web:
    build: .
    container_name: site_devops
    networks:
      - castelo_web
    restart: always

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - castelo_web
      - castelo_edge
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - obs
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - obs
    restart: always

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    networks:
      - obs

volumes:
  uptime-kuma-data:
  caddy_data:
  caddy_config:
  caddy_logs:
  crowdsec_data:
  prometheus_data:
  grafana_data:

networks:
  castelo_web:
    internal: true
  castelo_edge:
    driver: bridge
  obs:
    external: true
