version: "3.8"

services:
  caddy:
    image: caddy:alpine
    container_name: caddy_borda
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_logs:/var/log/caddy       # NOVO: Partilha os logs
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - castelo_edge
      - castelo_web
      - obs
    restart: always

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      # Instala as regras de segurança base e do Caddy
      - COLLECTIONS=crowdsecurity/caddy crowdsecurity/base-http-scenarios crowdsecurity/linux
    volumes:
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml
      - caddy_logs:/var/log/caddy:ro    # NOVO: Lê os logs partilhados
      - crowdsec_data:/var/lib/crowdsec/data
    networks:
      - obs
    restart: always

  web:
    build: .
    container_name: site_devops
    networks:
      - castelo_web
    restart: always

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - castelo_web
      - castelo_edge
    restart: always

volumes:
  uptime-kuma-data:
  caddy_data:
  caddy_config:
  caddy_logs:         # NOVO
  crowdsec_data:      # NOVO

networks:
  castelo_web:
    internal: true
  castelo_edge:
    driver: bridge
  obs:
    external: true